version: "3.9"

services:
  web:
    build: .
    container_name: fastapi-app
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./db:/app/db
    working_dir: /app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

